"""
Django settings for outbizzed project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.join(BASE_DIR, os.pardir))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = 'pl7a-@xd_$h((11i972v=d^%o_d!7#l4(s)ximmd!lcm2$4uh^'

DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', '*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'accounts',
    'events',
    'devices',
    'api',
    'calendars',
    'contacts',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'rest_auth',
    'rest_auth.registration',
    'debug_toolbar',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'outbizzed.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'outbizzed.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'outbizzed',
        'USER': 'outbizzu',
        'PASSWORD': 'Out_2018_BiZzZeD',
        'HOST': '192.168.88.250',
        'PORT': '5433',
    }
}

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')

MEDIA_URL = '/media/'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = (
    # "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

STATIC_URL = '/static/'

INTERNAL_IPS = '127.0.0.1'

SITE_ID = 1

# ===== django-allauth =====
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_CONFIRMATION_HMAC = False
SOCIALACCOUNT_ENABLED = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email', ],
        'AUTH_PARAMS': {'access_type': 'online', }
    }
}

# ===== django rest framework =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',  # comment it to disallow standard (web-app auth)
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
    ),
}

# ===== django-rest-auth =====
REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "api.serializers.UserSignUpSerializer",
}

# ==== google client / scope settings ====
GOOGLE_SCOPES = {
    "CALENDAR_PEOPLE": [
        #"https://www.googleapis.com/auth/contacts",
        "https://www.googleapis.com/auth/calendar",
        # ===== extra scopes =====
        #"https://www.googleapis.com/auth/plus.login",
        #"https://www.googleapis.com/auth/user.addresses.read",
        #"https://www.googleapis.com/auth/user.birthday.read",
        #"https://www.googleapis.com/auth/user.emails.read",
        #"https://www.googleapis.com/auth/user.phonenumbers.read",
        #"https://www.googleapis.com/auth/userinfo.email",
        #"https://www.googleapis.com/auth/userinfo.profile",
    ],
    "CALENDAR": ["https://www.googleapis.com/auth/calendar"],
    "CALENDAR_READ": ["https://www.googleapis.com/auth/calendar.readonly"],
    "PEOPLE": ["https://www.googleapis.com/auth/contacts"],
    "PEOPLE_READ": ["https://www.googleapis.com/auth/contacts.readonly"],
    "GOOGLE_LOGIN": ["https://www.googleapis.com/auth/plus.login",
                     "https://www.googleapis.com/auth/userinfo.email"],
}

GOOGLE_CLIENT_SECRET = {
    "CLIENT_ID": os.environ.get(
    "CLIENT_ID", "314834407539-ke52ed83dkm3544b65sde2ics5igm47m.apps.googleusercontent.com"),
    "PROJECT_ID": os.environ.get("PROJECT_ID", "teamicate"),
    "AUTH_URI": os.environ.get("AUTH_URI", "https://accounts.google.com/o/oauth2/auth"),
    "TOKEN_URI": os.environ.get("TOKEN_URI", "https://accounts.google.com/o/oauth2/token"),
    "AUTH_PROVIDER_X509_CERT_URL": os.environ.get(
    "AUTH_PROVIDER_X509_CERT_URL", "https://www.googleapis.com/oauth2/v1/certs"),
    #"CLIENT_SECRET": os.environ.get("CLIENT_SECRET", "ncw8TNzeoNneQwyhBTEbnWYq"),
    "CLIENT_SECRET": os.environ.get("CLIENT_SECRET", "xKgewZs64zvhDp2s4E8Dgu85"), # from json
    "REDIRECT_URIS": "http://localhost:8000/api/v1/user/google/credentials",
    "GOOGLE_LOGIN_REDIRECT": "http://localhost:8000/api/v1/user/google/login/v2",
}


FACEBOOK_APP_ID = os.environ.get("FACEBOOK_APP_ID", "1970742959643911")
FACEBOOK_APP_SECRET = os.environ.get("FACEBOOK_APP_SECRET", "12ba067f1b0596829fdffcf89075b96c")
FACEBOOK_SCOPES = ['email']
# FACEBOOK_REDIRECT_URL = 'https://localhost/'
FACEBOOK_REDIRECT_URL = 'https://f3f81ee2.ngrok.io/api/v1/user/fb/login/v2/'
# FACEBOOK_RESPONSE_TYPE = 'code%20token'
FACEBOOK_RESPONSE_TYPE = 'code'


FREEBUSY_DAYS_PERIOD = 7

SILENCED_SYSTEM_CHECKS = ['auth.W004']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(PROJECT_ROOT, './outbizzed.log'),
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
